name: CODE TEST

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: save code test history
        run: |
          pip install --upgrade pip
          python3 test.py

      
