name: CODE TEST

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: save code test history
        run: |
          pip install --upgrade pip
          python3 test.py
          echo ${{ !contains(github.event.head_commit.message) }}

      
