name: CODE TEST

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: create google api
        run: |
          touch google-service.json
      - name: Putting data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > google-services.json
      - name: save code test history
        run: |
          pip install --upgrade pip
          pip install --upgrade oauth2client 
          pip install gspread
          pip install PyOpenSSL
          python3 save_history.py ${{ github.actor }} ${{ github.event.head_commit.message }} ${{ github.sha  }}
